### ISSUE TITLE
Error while running tests

### ISSUE THREAD

**Issue by robertmircea** [helipilot50/aerospike-LDT-techniques#1]
I've just cloned the repo and tried to run mvn test on the project. Unfortunately, I received the following exception on test run:

```
testPoll(com.aerospike.examples.ldt.LDTQueueTest)  Time elapsed: 0.01 sec  <<< ERROR!
com.aerospike.client.AerospikeException: Error Code 100: ./queue.lua:35: attempt to index local 'firstElement' (a nil value)
    at com.aerospike.client.command.ReadCommand.handleUdfError(ReadCommand.java:154)
    at com.aerospike.client.command.ReadCommand.parseResult(ReadCommand.java:118)
    at com.aerospike.client.command.SyncCommand.execute(SyncCommand.java:56)
    at com.aerospike.client.AerospikeClient.execute(AerospikeClient.java:1016)
    at com.aerospike.examples.ldt.LDTQueue.poll(LDTQueue.java:143)
    at com.aerospike.examples.ldt.LDTQueueTest.testPoll(LDTQueueTest.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Do you have any pointers on how to get past this error?

All errors summary:

```
Tests in error:
  testPut(com.aerospike.examples.ldt.LDTMapTest): Client timeout: timeout=0 iterations=2 failedNodes=2 failedConns=0 lastNode=null
  testGet(com.aerospike.examples.ldt.LDTMapTest): Client timeout: timeout=0 iterations=2 failedNodes=2 failedConns=0 lastNode=null
  testEntrySet(com.aerospike.examples.ldt.LDTMapTest): Client timeout: timeout=0 iterations=2 failedNodes=2 failedConns=0 lastNode=null
  testRemove(com.aerospike.examples.ldt.LDTQueueTest): Unexpected exception, expected<java.util.NoSuchElementException> but was<com.aerospike.client.AerospikeException>
  testPoll(com.aerospike.examples.ldt.LDTQueueTest): Error Code 100: ./queue.lua:35: attempt to index local 'firstElement' (a nil value)
```

**Comment by helipilot50** [comment]
the tests all assume that you have a cluster at "localhost". Do you have the cluster address set correctly? Ping me if you need help

**Comment by robertmircea** [comment]
I am running the Java tests from a mac against an Aerospike server started
in a vagrant vm - default configuration - as it was downloaded from
Aerospike website.

Robert

**Comment by helipilot50** [comment]
Pul the latest and see if this helps
